### ISSUE TITLE
Cannot glMapBufferOES with GL_STREAM_DRAW

### ISSUE THREAD

**Issue by b-pass** [raspberrypi/userland#246]
In raspberrypi/userland/interface/khronos/glxx/glxx_client.c
Line 385 & 397
... If glBufferData() is called with GL_STREAM_DRAW then the buffer's cached size is set to zero.

In raspberrypi/userland/interface/khronos/ext/gl_oes_map_buffer.c
Line 66 & Line 94
... If the cached size is zero, then the GL_INVALID_OPERATION is raised and the buffer is not mapped.

The net effect being that you can't call glMapBufferOES on a buffer that was set up using GL_STREAM_DRAW.  I think it ought to work fine though, and it seems like a small bug on glxx_client.c line 385.

**Comment by JamesH65** [comment]
@timg236 Anything you can help with? It's quite an old issue...

**Comment by timg236** [comment]
I think @b-pass is right. This looks like a bug in the userland glxx_client.c. I hacked hello_triangle.c to map, modify and unmap the buffer and was able to reproduce the failure. The trivial fix of accepting GL_STREAM_DRAW in glxx_client.c line 385 resolved the issue.

The legacy driver is deprecated but I think the fix is simple  enough that we should just fix it.

It would be useful to know if there is test-case for this.

**Comment by JamesH65** [comment]
@timg236 Can you push the change as a PR? No idea about a test case.
