### ISSUE TITLE
Raspivid raw frame data output

### ISSUE THREAD

**Issue by jeffism** [raspberrypi/userland#28]
Requesting option for raspivid to output raw frame data for image processing/analysis. Even if we can only use low resolution or low frame rate to not overload the Pi's limited CPU power, it'll make for a cheap, compact unit for computer vision projects.

I have already tried modifying https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiVid.c#L695 to a different codec listed in https://github.com/raspberrypi/userland/blob/master/interface/mmal/mmal_encodings.h (RGBA would be a good candidate) but the Pi doesn't appear to support anything other than H.264, upon execution it throws a "mmal_vc_port_info_set failed EINVAL" error.

**Comment by Ruffio** [comment]
@jeffism is this still an issue?

**Comment by waveform80** [comment]
There's a raspividyuv now provided in userland which looks like it ought to do this (I'm not sure it's in the current packaged firmware from Raspbian, but it should be easy enough to build from a clone of userland).

**Comment by popcornmix** [comment]
Sounds like the issue has solutions now.

**Comment by joshnroy** [comment]
I've noticed the -rf rgb flag still gives out what looks to be yuv data. Is the -rf rgb flag no longer supported, or did I mess something else up (maybe in my install?)?

**Comment by 6by9** [comment]
(It's normally better to open a new issue rather than post on a closed issue that is only partially relevant)

At a guess it's the fact that the processing for -r / --raw (https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/raspicam/RaspiVid.c#L860) sets the raw format to YUV, so 
```raspivid -rf rgb -r file.rgb```
will output YUV, whilst
```raspivid -r file.rgb -rf rgb```
Somewhat yucky, but that's the way it was written.

I guess that ought to be cleaned up so that the default is set at start of day, and -r / --raw then doesn't reset it. There's a task outstanding to do a big cleanup of raspicam, so it can be addressed at the same time (which is why this should have been a new issue raised. As it is this set of comments is likely to get lost).
