### ISSUE TITLE
Requesting buffer size messes up client state

### ISSUE THREAD

**Issue by ldmnyblzs** [raspberrypi/userland#323]
When `glGetBufferParameteriv` is called with `GL_BUFFER_SIZE`, it creates and stores a `GLXX_BUFFER_INFO_T` but sets `id` and `cached_size` only. `mapped_pointer` and `mapped_size` get random values. This makes every subsequent call to `glBufferData` fail and `glGetBufferPointervOES` also returns false information from this point on.

**Comment by popcornmix** [comment]
We don't have anyone who really knows this code, and GL is being replaced with the open-source arm side driver. I'm just guessing, but this code does look a little suspicious:
https://github.com/raspberrypi/userland/blob/master/interface/khronos/glxx/glxx_client.c#L2110

Could you try inserting:
```glxx_buffer_info_get(state, target, &buffer);```
before the
``buffer.cached_size = params[0];``
line, and rebuild userland?

**Comment by JamesH65** [comment]
@popcornmix no response from OP, but should we be thinking of testing this fix? Or just wont fix the issue?

**Comment by JamesH65** [comment]
@timg236 Any thoughts?

**Comment by timg236** [comment]
I think the current implementation is wrong. It's attempting to updated it's cached copy of the buffer size but should not be modifying mapped_size and mapped_values. 
As @popcornmix mentions the fix is probably to call info_get first and then modify just the cached size before calling info_set.

It's the legacy driver but the fix is simple and low risk.

**Comment by JamesH65** [comment]
@timg236 Can you bung in a PR so it can be reviewed/merged?
