### ISSUE TITLE
Use nproc instead of 6 in buildme

### ISSUE THREAD

**Issue by LukeSkyw** [raspberrypi/userland#377]
Some people have more than 6 cores on their CPU.
Why not use nproc in buildme like so:
``make -j `nproc` ``

**Comment by 6by9** [comment]
Agreed that that would be a sensible thing to do.
Feel free to create a pull request that will change it.

**Comment by pelwell** [comment]
Isn't it the case that nproc*1.5 is a better heuristic?

**Comment by 6by9** [comment]
TBH userland is generally fairly quick to compile anyway. Using nproc would avoid crippling a machine with <4 cores.
How i/o bound is the "generic system"? Do you assume the data is on an SSD and therefore very swift, or is it a slow HDD in which case a larger multiple of nproc would be appropriate.

I think everybody has their own rule - nproc+1 is another I know to be quite popular. I think this is a case of choose something sensible.

**Comment by JamesH65** [comment]
Once upon a time I did actually do some testing, and x1.5 was spot on, but
that was spinning rust storage, SSD's may well be different. Note the
difference was x1 to x1.5 was fairly small but there.

On 1 March 2017 at 16:43, 6by9 <notifications@github.com> wrote:

> TBH userland is generally fairly quick to compile anyway. Using nproc
> would avoid crippling a machine with <4 cores.
> How i/o bound is the "generic system"? Do you assume the data is on an SSD
> and therefore very swift, or is it a slow HDD in which case a larger
> multiple of nproc would be appropriate.
>
> I think everybody has their own rule - nproc+1 is another I know to be
> quite popular. I think this is a case of choose something sensible.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_userland_issues_377-23issuecomment-2D283395968&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=xltpMuc1HJ9xpN0YOnAhgj3dAYZF_53rTlVapp7EKn8&s=GnoPs-Tp73DjVvsGgm_U1XQ5lOMqLMa7Api_NAEo2KU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHTAkCnpbFeOJi345XWdhWnUMEfWFks5rhaBOgaJpZM4MP1m0&d=DwMFaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=xltpMuc1HJ9xpN0YOnAhgj3dAYZF_53rTlVapp7EKn8&s=HMP3dst73gRVZKr0V7AG6yySP45kf1JKeXl0Fnk1wLI&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by Ferroin** [comment]
There are too many variables involved.  For traditional HDD's on IDE or SATA, the ideal number usually is about 1.5 when using GCC, but it goes down when using clang (Clang compiles things faster, so it spends more time waiting on IO, but having more processes waiting on IO slows things down).  On most SCSI HDD's, it's actually almost 2 for GCC.  On SATA and SCSI SSD's it's typically 1+nproc, and for NVMe SSD's or NVDIMM's (both of which are relatively rare still), it's actually exactly nproc.  IOW, the faster your storage and the faster your compiler, the lower the ideal value.

The standard for most projects that automatically parallelize though is exactly nproc, since it means they can take advantage of the whole CPU, but aren't likely to edge out other stuff running on the system.
