### ISSUE TITLE
Question: Is dtoverlay still active and maintained here?

### ISSUE THREAD

**Issue by bclouser** [raspberrypi/userland#484]
Hello, 

I see that _opensrc/helpers/libfdt_ is a snapshot taken 3 years ago which got me wondering if there were plans afoot to update this to the latest?  I am ultimately wondering about the 'dtoverlay' tool. Is this the best place to get and build 'dtoverlay' or is it maintained elsewhere?

Thanks,
  Ben

**Comment by pelwell** [comment]
This is the canonical source repo for the dtoverlay utility. libfdt hasn't changed because this snapshot still does what we want. A rainy-day job would be to pull in the latest version and refactor the dtoverlay library to make more use of the now-standard overlay functions, but it's not high on the list of priorities.

**Comment by JamesH65** [comment]
I'm thinking this can be closed as its a question that has been answered?
