### ISSUE TITLE
CM4 host

### ISSUE THREAD

**Issue by gregoryjaooi** [raspberrypi/userland#695]
Problem : 
Some users are using CM4 and the source codes are using bcm_host_is_model_pi4() function call to
check for BCM2711 to differentiate from other older Pi Models.
As such, the same application has error/issues running on CM4 (0x14) or PI400 (0x13) while
on PI4 (x11) there are no issues at all.

/* Returns the type of the Pi being used
*/
int bcm_host_is_model_pi4(void)
{
   return bcm_host_get_model_type() == 0x11 ? 1 : 0;
}

Or may be there should be a better work around that I am not aware of.

**Comment by pelwell** [comment]
@popcornmix may have some thoughts on the matter, but as you say I think this function makes more sense as a way of detecting any member of the Pi 4 family, i.e. 4B, 400 and CM4. This is equivalent to checking if the processor is a BCM2711, so I think it should be implemented in that way. While looking at this I also noticed that the list of processor types include BCM2838 - our guess at the Broadcom name for what turned out to be called BCM2711. `BCM_HOST_PROCESSOR_BCM2711` should be included as an alias.

**Comment by pelwell** [comment]
See https://github.com/raspberrypi/userland/pull/696.

**Comment by gregoryjaooi** [comment]
This issue can be closed as CM4
is running very well now after raspi-update.
Thanks.
