### ISSUE TITLE
RaspiCam - setting preview size affects preview origin

### ISSUE THREAD

**Issue by JamesH65** [raspberrypi/userland#98]
Odd one - it appear when you set certain preview sizes, the origin of the preview window can move. This is unexpected - preview should scale up/down, but not move it's origin.

It may be down to trying to maintain aspect ratios.

**Comment by Ruffio** [comment]
@JamesH65 whats the status on this issue?

**Comment by Ruffio** [comment]
@JamesH65 whats the status on this issue?

**Comment by JamesH65** [comment]
No longer have access to required source. @6by9

**Comment by Ruffio** [comment]
@JamesH65, then I suggest that you no longer are assigned to this issue.
@6by9 ???

**Comment by JamesH65** [comment]
Feel free to reassign, if you can find someone to look at it.

**Comment by 6by9** [comment]
@JamesH65 Expected behaviour.
The preview window will retain the source image aspect ratio and symmetrically letterbox/pillarbox.
If your window aspect ratio doesn't match that of your source image, it will then move up/down/left/right.

There is the option to ignore aspect ratio with the noaspect field within MMAL_DISPLAYREGION_T - https://github.com/raspberrypi/userland/blob/master/interface/mmal/mmal_parameters_video.h#L191. The source image will then always be stretched to fit the display window.

**Comment by Ruffio** [comment]
So this should be closed as it is working as designed?

**Comment by JamesH65** [comment]
I'm wondering why I opened this issue. Clearly the origin will move for different resolutions, so I am not sure what/why I posted the issue. I suspect my description of the issues I saw is not accurate, but it was so long ago I cannot remember what the exact issue was. My suspicion is the 'centre' of the image changes for some preview sizes, not the origin. But I am going to close it anyway.
